# Generated by Django 4.2.20 on 2025-03-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome do Item")),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "quantidade",
                    models.IntegerField(
                        default=0, verbose_name="Quantidade em Estoque"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Categoria"
                    ),
                ),
                (
                    "localizacao",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Localização",
                    ),
                ),
                (
                    "estoque_minimo",
                    models.IntegerField(default=0, verbose_name="Estoque Mínimo"),
                ),
            ],
        ),
    ]
